# Etapa 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY GerenciadorTarefas.API.csproj ./
RUN dotnet restore
COPY . ./
RUN ls -l /app/out && file /app/out/GerenciadorTarefas.API.dll

# Etapa 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out ./
EXPOSE 8080
ENTRYPOINT ["dotnet", "GerenciadorTarefas.API.dll"]